version: '3.7'
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: inbiskom_app
    container_name: inbiskom-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - inbiskom
    env_file:
      - ./.env
  db:
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'mysql --database=${DB_DATABASE} --password=${DB_PASSWORD} --execute="SELECT count(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B',
        ]
      interval: 30s
      timeout: 10s
      retries: 4
    image: mariadb
    container_name: inbiskom-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_USER: '${DB_USERNAME}'
      SERVICE_TAGS: dev
      SERVICE_NAME: mariadb
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 8079:${DB_PORT}
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - inbiskom
    env_file:
      - ./.env
  nginx:
    image: nginx:1.17-alpine
    container_name: inbiskom-nginx
    restart: unless-stopped
    ports:
      - 8081:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - inbiskom

networks:
  inbiskom:
    driver: bridge
